name: 夸克网盘自动签到脚本-235657808

on:
  schedule:
    # 定时执行，默认UTC时区， 中国时区需要+8小时， 中国时间每天7:40执行
    - cron: '40 23 * * *'

  workflow_dispatch:  # 允许手动触发
jobs:

  run-python:
    runs-on: ubuntu-latest  # 运行环境：Ubuntu 最新版
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检查代码

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
          cache-dependency-glob: false


      - name: Check UV version
        run: uv --version  # 检查 UV 版本

      - name: Sync dependencies with UV
        run: uv sync  # 使用 UV 同步依赖

      - name: Run Python script with UV
        env:
          QUARK_KPS: Tj5o99cfi2c7GIA8OSkuL7wEtwFG0zM4c2r4bxfALXJMpSVfeiUlkXnIU567WtH2wYCs1H2Zdc%2FduFpEFKsptwNhIeto2hZdT6jQECMImGCNxFiTsL9AJOp%2BRjqZ%2BQT47C4%3D
          QUARK_SIGN: Tj6u1TF1K6rxH3QTYJ4nvyeogUaSq8hz1Q%2BfLSCadWOEz1hbwYhBMEr1CmKRPiGXBCo%3D
          QUARK_VCODE: 1770642384216
          SMTP_SERVER: smtp.qq.com
          SMTP_PORT: 587
          EMAIL: 235657808@qq.com
          PASSWORD: moiseqedrwndcbae
        run: uv run main.py  # 使用 UV 运行 Python 脚本
